notifications:
  email: false

matrix:
  include:
    - os: linux
      sudo: required
    - os: osx

language: node_js

node_js:
  - "8.2.1"  # Current stable Electron version
  - "8.9"    # LTS
  - "9"      # Current

install:
  - ./.travis/install.sh
  - npm install
  - npm run configure
  - npm run build

deploy:
  provider: script
  script: ./.travis/deploy.sh
  on:
    tags: true
